name: CreazyKits
version: '1.0'
main: pl.creazy.creazykits.CreazyKits
api-version: '1.21'
authors: [ Dawid Ratajczak ]
website: creazy.pl
depend:
  - CreazyLib
commands:
  kit:
    description: manage kits
